name: Agent Nudge

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  nudge:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Copilot on idle RFC PRs
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            const prs = await github.paginate(github.rest.pulls.list, { owner, repo, state: 'open', per_page: 100 });
            const now = new Date();
            const IDLE_MINS = 5; // TEMP: nudge if idle > 5 minutes (testing)
            for (const pr of prs) {
              const text = (pr.title || '') + '\n' + (pr.body || '');
              const hasRfc = /(RFC[- ]\d{4})/i.test(text);
              if (!hasRfc) continue;
              const isCopilotAuthor = /copilot/i.test(pr.user?.login || '');
              const isCopilotBranch = /copilot\//i.test(pr.head?.ref || '');
              const assignees = (pr.assignees || []).map(a => (a.login||'').toLowerCase());
              const isCopilotAssigned = assignees.includes('copilot');
              if (!(isCopilotAuthor || isCopilotBranch || isCopilotAssigned)) continue;

              // Skip very large PRs; PR Guard will handle guidance
              if ((pr.additions || 0) > 1200 || (pr.changed_files || 0) > 50) continue;

              const updated = new Date(pr.updated_at);
              const idleMins = Math.round((now - updated)/60000);
              if (idleMins < IDLE_MINS) continue;

              // Avoid spam: only nudge if no prior nudge within 6 hours
              const comments = await github.paginate(github.rest.issues.listComments, { owner, repo, issue_number: pr.number, per_page: 100 });
              const recentNudge = comments.find(c => c.body?.includes('<!-- nudge:copilot -->') && ((now - new Date(c.created_at)) / 3600000) < 6);
              if (recentNudge) continue;

              const msg = [
                '<!-- nudge:copilot -->',
                '@copilot friendly ping to continue per .github/copilot-instructions.md:',
                '- Next batch: 3–5 files, under ~300 LOC.',
                '- Post a checkpoint summary after the batch.',
                'If blocked, comment with what’s missing and propose a small next step.'
              ].join('\n');
              await github.rest.issues.createComment({ owner, repo, issue_number: pr.number, body: msg });
              try { await github.rest.issues.addLabels({ owner, repo, issue_number: pr.number, labels: ['in-progress'] }); } catch {}
            }