name: Cleanup Actions runs

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner; const repo = context.repo.repo;
            const now = Date.now();
            const failedCutoffMs = 2 * 60 * 60 * 1000; // 2 hours
            const successCutoffMs = 2 * 24 * 60 * 60 * 1000; // 2 days

            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, { owner, repo, per_page: 100 });
            let deleted = 0;
            for (const run of runs) {
              const ageMs = now - new Date(run.updated_at).getTime();
              const isSuccess = run.conclusion === 'success';
              const isFailed = ['failure','timed_out','cancelled'].includes(run.conclusion || '');
              if ((isFailed && ageMs > failedCutoffMs) || (isSuccess && ageMs > successCutoffMs)) {
                try {
                  await github.rest.actions.deleteWorkflowRun({ owner, repo, run_id: run.id });
                  deleted++;
                } catch (e) {
                  // ignore protected runs
                }
              }
            }
            core.info(`Deleted ${deleted} old runs`);