name: Implementation Agent (deprecated)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "This workflow is deprecated. Use GitHub Copilot Coding Agent as documented in AGENTS.md."
