name: Push sanity

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create test change
        run: |
          ts=$(date -u +%Y%m%dT%H%M%SZ)
          echo "push sanity at $ts" > .github/push-sanity.txt
          git add .github/push-sanity.txt
          git commit -m "chore: push sanity $ts"
      - name: Push to new branch
        env:
          REPO: ${{ github.repository }}
        run: |
          BRANCH="bot/push-sanity-${GITHUB_RUN_ID}"
          git checkout -b "$BRANCH"
          # Ensure remote uses token
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
          git push --set-upstream origin "$BRANCH"
          echo "pushed_branch=$BRANCH" >> $GITHUB_OUTPUT