name: RFC On PR Open

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to process (for manual run)"
        required: false
        type: number

jobs:
  start:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Extract RFC IDs
        id: ids
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const owner = context.repo.owner; const repo = context.repo.repo;
            let title = '', body = '';
            if (context.eventName === 'pull_request') {
              title = context.payload.pull_request?.title || '';
              body = context.payload.pull_request?.body || '';
            } else if (context.eventName === 'workflow_dispatch') {
              const prn = context.payload?.inputs?.pr_number ? Number(context.payload.inputs.pr_number) : NaN;
              if (!isNaN(prn)) {
                const pr = await github.rest.pulls.get({ owner, repo, pull_number: prn });
                title = pr.data.title || '';
                body = pr.data.body || '';
                core.exportVariable('MANUAL_PR_NUMBER', String(prn));
              }
            }
            const text = `${title}\n${body}`;
            const matches = Array.from(text.matchAll(/RFC[- ](\d{4})/gi)).map(m => m[1]);
            const ids = Array.from(new Set(matches)).join(',');
            core.setOutput('ids', ids);
      - name: Mark Implementing and label linked issue
        if: steps.ids.outputs.ids != ''
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruamel.yaml ruamel.yaml.clib
          python - << 'PY'
          from pathlib import Path
          from ruamel.yaml import YAML
          from io import StringIO
          import re
          ids = [s for s in '${{ steps.ids.outputs.ids }}'.split(',') if s]
          yaml = YAML()
          idx = Path('docs/RFC/index.yaml')
          data = yaml.load(idx.read_text(encoding='utf-8'))
          changed = False
          for rid in ids:
            meta = data['rfcs'].get(rid)
            if meta and meta.get('state') in ('Approved','Draft'):
              meta['state'] = 'Implementing'
              changed = True
            # also update front-matter state in the RFC markdown file(s)
            for f in Path('docs/RFC').glob(f'{rid}-*.md'):
              txt = f.read_text(encoding='utf-8')
              txt2 = re.sub(r'(state:\s*)(Draft|Approved|Review|Rejected)', r'\1Implementing', txt, count=1)
              if txt2 != txt:
                f.write_text(txt2, encoding='utf-8')
          if changed:
            buf = StringIO()
            yaml.dump(data, buf)
            idx.write_text(buf.getvalue(), encoding='utf-8')
          PY
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/RFC/index.yaml docs/RFC/*.md
          git commit -m "chore(rfc): mark RFC(s) ${{ steps.ids.outputs.ids }} Implementing" || echo "No changes"
          git push || true
      - name: Label related task issue as in-progress
        if: steps.ids.outputs.ids != ''
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner; const repo = context.repo.repo;
            const ids = '${{ steps.ids.outputs.ids }}'.split(',').filter(Boolean);
            const prNumber = process.env.MANUAL_PR_NUMBER ? Number(process.env.MANUAL_PR_NUMBER) : (context.payload.pull_request?.number);
            for (const id of ids) {
              const q = `repo:${owner}/${repo} is:issue state:open RFC-${id} in:title`;
              const res = await github.rest.search.issuesAndPullRequests({ q });
              if (res.data.total_count === 0) continue;
              const issue = res.data.items[0];
              await github.rest.issues.addLabels({ owner, repo, issue_number: issue.number, labels: ['in-progress'] }).catch(()=>{});
              if (prNumber) {
                await github.rest.issues.createComment({ owner, repo, issue_number: issue.number, body: `Tracking PR #${prNumber}` }).catch(()=>{});
              }
            }
