name: Stale Triage

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch: {}

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          days-before-close: 3
          stale-issue-message: >
            This issue has been marked stale due to inactivity. If this is still relevant, please add a comment or apply the label `keep-open`.
          close-issue-message: >
            Closing due to inactivity. Reopen if needed.
          stale-pr-message: >
            This PR has been marked stale due to inactivity. If this is still relevant, please add a comment or apply the label `keep-open`.
          close-pr-message: >
            Closing due to inactivity. Reopen if needed.
          exempt-issue-labels: keep-open, in-progress, coordinator, rfc
          exempt-pr-labels: keep-open, in-progress, rfc
